package net.mfilm.utils

/**
 * Created by tusi on 5/14/17.
 */
enum class IndexTags {
    FRAGMENT_HOME,
    FRAGMENT_FAV,
    FRAGMENT_SEARCH,
    FRAGMENT_HISTORY,
    FRAGMENT_MANGA_INFO,
    FRAGMENT_CATEGORY,
    FRAGMENT_CHAPTER_INFO,
    FRAGMENT_CHAPTER_IMAGES,
    FRAGMENT_MANGA,
    FRAGMENT_FULL_READ,
    FRAGMENT_SETTINGS,
    FRAGMENT_ABOUT
}

enum class DialogMenus {
    SHARE, FAVORITES
}